SCR_EntityCatalogMultiListEntry {
 m_sIdentifier "Eppsi Patches"
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{6A2D31093DE526D0}" {
   m_sEntityPrefab "{01B998B9887692B8}Prefabs/Items/Equipment/Patches/Eppsis/Patch_CHMA_DOORDASH.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{02D77B6CB1694859}" {
     m_bEnabled 1
     m_eItemType EQUIPMENT
     m_eItemMode DEFAULT
     m_eArsenalGameModeTypes CAMPAIGN
     m_iSupplyCost 0
     m_eRequiredRank PRIVATE
     m_bUseMilitarySupplyAllocation 1
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{6A2D31093DE526D7}" {
   m_sEntityPrefab "{B071DB9A446B6535}Prefabs/Items/Equipment/Patches/Eppsis/Patch_CHMA_MOTHERSHIP.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{4EDB93EDBFD29FDD}" {
     m_bEnabled 1
     m_eItemType EQUIPMENT
     m_eItemMode DEFAULT
     m_eArsenalGameModeTypes CAMPAIGN
     m_iSupplyCost 0
     m_eRequiredRank PRIVATE
     m_bUseMilitarySupplyAllocation 1
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{6A2D310903AD4E34}" {
   m_sEntityPrefab "{94859097E38482D8}Prefabs/Items/Equipment/Patches/Eppsis/Patch_CHMA_ZINGER.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{B46C2C37149BB85D}" {
     m_bEnabled 1
     m_eItemType EQUIPMENT
     m_eItemMode DEFAULT
     m_eArsenalGameModeTypes CAMPAIGN
     m_iSupplyCost 0
     m_eRequiredRank PRIVATE
     m_bUseMilitarySupplyAllocation 1
    }
   }
  }
 }
}
