SCR_EntityCatalogMultiListEntry {
 m_sIdentifier "Eppsi Patches"
 m_aEntities {
  SCR_EntityCatalogEntry "{6A2D31093DE526D0}" {
   m_sEntityPrefab "{01B998B9887692B8}Prefabs/Items/Equipment/Patches/Eppsis/Patch_CHMA_DOORDASH.et"
  }
  SCR_EntityCatalogEntry "{6A2D31093DE526D7}" {
   m_sEntityPrefab "{B071DB9A446B6535}Prefabs/Items/Equipment/Patches/Eppsis/Patch_CHMA_MOTHERSHIP.et"
  }
  SCR_EntityCatalogEntry "{6A2D310903AD4E34}" {
   m_sEntityPrefab "{94859097E38482D8}Prefabs/Items/Equipment/Patches/Eppsis/Patch_CHMA_ZINGER.et"
  }
 }
}
