SCR_EntityCatalogMultiListEntry {
 m_sIdentifier "Auto Patches"
 m_aEntities {
  SCR_EntityCatalogEntry "{6988811658B6F498}" {
   m_sEntityPrefab "{A6C6CCC7E5725041}Prefabs/Items/Equipment/Patches/Autos/Patch_CHMA_AUTO_ADHD.et"
  }
  SCR_EntityCatalogEntry "{69F16AEF54B84203}" {
   m_sEntityPrefab "{A72107B17BAE36C3}Prefabs/Items/Equipment/Patches/Autos/Patch_CHMA_WEYLAND_YUTANI.et"
  }
 }
}
